spring.application.name=Cleanus_mockapi
server.port=8081

# Mock Api Key
mockapi.api-key=dev-key-123

# ???? ?? ??
mockapi.tx.min-per-minute=0
mockapi.tx.max-per-minute=3
mockapi.tx.min-amount=-50000
mockapi.tx.max-amount=200000
mockapi.tx.shops=????,??? CU,???,?????


#MariaDB ?? ??
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3308/mockapi_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true


# UTC
spring.jackson.time-zone=UTC