# Main server port
server.port=8000

# Mock API (external provider simulator)
cleanus.mock.base-url=http://localhost:8001
cleanus.mock.api-key=dev-key-123

# Node.js Anchoring Server (Blockchain side)
cleanus.node.base-url=http://localhost:8002
cleanus.node.api-key=prod-anchor-key-xxx

cleanus.anchor.node.connect-timeout-ms=3000
cleanus.anchor.node.read-timeout-sec=10

cleanus.anchor.node.retry.max-attempts=3
cleanus.anchor.node.retry.backoff-ms=200

# Batch (seal) thresholds
cleanus.batch.size-threshold=50
cleanus.batch.time-days=14

# Schedular settings

# Batch sealing : run daily at 02:00
cleanus.batch.seal.cron=0 0 2 * * *
# Anchoring : run every 10 minutes
cleanus.anchor.run.cron=0 */10 * * * *
# Receipt verification : run every 1 minute
cleanus.verify.run.cron=0 * * * * *
cleanus.verify.max-retries=0

# Blockchain RPC endpoint
cleanus.chain.rpc-url=http://localhost:8545

# JPA / Hibernate configuration
spring.datasource.url=jdbc:mariadb://localhost:3308/cleanus
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# SendGrid mail settings

# (Development only) use env variable for production
sendgrid.api-key= ${SENDGRID_API_KEY:}
# (For real)
# spring.sendgrid.api-key=${SENDGRID_API_KEY}
app.mail.from=ggn327641@gmail.com